"""
Multi-query, multi-index vector search module for MongoDB Atlas.

This module provides functions to perform semantic similarity searches
across THREE vector search indexes (brief / detailed / regional) using
MULTIPLE query phrasings generated by the query expander.  Results are
merged, deduplicated, and ranked by highest score.

Prerequisites — three Atlas Vector Search indexes:
    embedding_brief_index    on field: embedding_brief     (384-dim, cosine)
    embedding_detailed_index on field: embedding_detailed  (384-dim, cosine)
    embedding_regional_index on field: embedding_regional  (384-dim, cosine)

Functions:
    vector_search_single: Run a single $vectorSearch on one index
    multi_search: Expand query, search all indexes, merge & deduplicate
"""

import logging
from datetime import datetime
from typing import List, Dict, Any, Optional

from pymongo.errors import PyMongoError, OperationFailure

from multimedia_rag.ingestion.embedder import generate_embedding
from multimedia_rag.ingestion.mongo_store import get_db
from multimedia_rag.query.expander import expand_query
from multimedia_rag import config

logger = logging.getLogger(__name__)

# Three vector search index names and the corresponding document fields
_INDEX_MAP = [
    ("embedding_brief_index", "embedding_brief"),
    ("embedding_detailed_index", "embedding_detailed"),
    ("embedding_regional_index", "embedding_regional"),
]


def _log(msg: str) -> None:
    """Print a timestamped log message."""
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    print(f"[{ts}] {msg}")


# ---------------------------------------------------------------------------
# Low-level single-index search
# ---------------------------------------------------------------------------

def vector_search_single(
    query_embedding: List[float],
    index_name: str,
    path: str,
    top_k: int = 25,
    filter_dict: Optional[Dict[str, Any]] = None,
) -> List[Dict[str, Any]]:
    """
    Run a single $vectorSearch aggregation on one index.

    Args:
        query_embedding: 384-dim embedding vector for the query.
        index_name: Name of the Atlas Vector Search index.
        path: Document field that stores the embedding array.
        top_k: Maximum number of results to return.
        filter_dict: Optional MongoDB pre-filter for the search.

    Returns:
        List[Dict]: Search results with fields _id, caption_brief,
            caption_detailed, caption_regional, cam_id, timestamp,
            gdrive_url, and score.

    Raises:
        OperationFailure: If the index does not exist.
        PyMongoError: If the database operation fails.
    """
    if not query_embedding:
        raise ValueError("Query embedding cannot be empty")
    if len(query_embedding) != config.EMBEDDING_DIMENSION:
        raise ValueError(
            f"Embedding must be {config.EMBEDDING_DIMENSION} dims, "
            f"got {len(query_embedding)}"
        )

    try:
        db = get_db()
        collection = db[config.COLLECTION_FRAME_EMBEDDINGS]

        vs_stage: Dict[str, Any] = {
            "$vectorSearch": {
                "index": index_name,
                "path": path,
                "queryVector": query_embedding,
                "numCandidates": config.NUM_CANDIDATES,
                "limit": top_k,
            }
        }
        if filter_dict:
            vs_stage["$vectorSearch"]["filter"] = filter_dict

        pipeline = [
            vs_stage,
            {
                "$project": {
                    "_id": 1,
                    "caption_brief": 1,
                    "caption_detailed": 1,
                    "caption_regional": 1,
                    "cam_id": 1,
                    "timestamp": 1,
                    "frame_image": 1,
                    "gdrive_url": 1,
                    "score": {"$meta": "vectorSearchScore"},
                }
            },
        ]

        return list(collection.aggregate(pipeline))

    except OperationFailure as e:
        err = str(e).lower()
        if "index not found" in err or "no such index" in err:
            _log(f"WARNING: Vector index '{index_name}' not found — skipping")
            return []
        _log(f"ERROR: Vector search on '{index_name}' failed: {e}")
        return []
    except PyMongoError as e:
        _log(f"ERROR: DB error during vector search on '{index_name}': {e}")
        return []


# ---------------------------------------------------------------------------
# High-level multi-query, multi-index search
# ---------------------------------------------------------------------------

def multi_search(
    user_query: str,
    top_k: int = 25,
) -> List[Dict[str, Any]]:
    """
    Run expanded multi-query search across all three vector indexes.

    Steps:
        1. Expand the user query into 6 phrasings via Ollama.
        2. Generate an embedding for each phrasing.
        3. For each embedding, search all three indexes (6 x 3 = up to 18 runs).
        4. Merge all results, deduplicate by _id keeping the highest score.
        5. Sort by score descending and return top_k results.

    Args:
        user_query: Natural-language search query.
        top_k: Maximum number of merged results to return (default 25).

    Returns:
        List[Dict]: Deduplicated results sorted by score descending.
            Each dict contains _id, caption_brief, caption_detailed,
            caption_regional, cam_id, timestamp, gdrive_url, score,
            and matched_query (the query phrasing that produced the
            highest score for that frame).

    Example:
        >>> results = multi_search("person with red backpack")
        >>> results[0]["score"]
        0.94
    """
    # Step 1 — expand
    queries = expand_query(user_query)
    _log(f"Running {len(queries)} queries x {len(_INDEX_MAP)} indexes "
         f"= up to {len(queries) * len(_INDEX_MAP)} vector searches...")

    # Step 2 — embed each query
    query_embeddings: List[tuple] = []  # (query_text, embedding)
    for q in queries:
        try:
            emb = generate_embedding(q)
            query_embeddings.append((q, emb))
        except Exception as e:
            _log(f"WARNING: Could not embed query '{q[:60]}': {e}")

    if not query_embeddings:
        _log("ERROR: No valid query embeddings — returning empty results")
        return []

    # Step 3 — search each (query, index) combination
    all_hits: List[Dict[str, Any]] = []
    searches_run = 0

    for q_text, q_emb in query_embeddings:
        for idx_name, idx_path in _INDEX_MAP:
            hits = vector_search_single(
                query_embedding=q_emb,
                index_name=idx_name,
                path=idx_path,
                top_k=top_k,
            )
            for hit in hits:
                hit["matched_query"] = q_text
            all_hits.extend(hits)
            searches_run += 1

    _log(f"Completed {searches_run} vector searches — "
         f"{len(all_hits)} raw hits before dedup")

    # Step 4 — merge & deduplicate, keep highest score per _id
    best: Dict[str, Dict[str, Any]] = {}
    for hit in all_hits:
        fid = hit.get("_id")
        if fid is None:
            continue
        existing = best.get(fid)
        if existing is None or hit.get("score", 0) > existing.get("score", 0):
            best[fid] = hit

    # Step 5 — sort & trim
    merged = sorted(best.values(), key=lambda x: x.get("score", 0), reverse=True)
    results = merged[:top_k]

    _log(f"Found {len(results)} unique candidates (top_k={top_k})")
    return results


# ---------------------------------------------------------------------------
# Legacy helper kept for backward compatibility
# ---------------------------------------------------------------------------

def vector_search(
    query_embedding: List[float],
    top_k: int = None,
    filter_dict: Optional[Dict[str, Any]] = None,
) -> List[Dict[str, Any]]:
    """
    Legacy single-index vector search (kept for backward compatibility).

    Searches the embedding_brief_index by default.

    Args:
        query_embedding: 384-dim embedding vector.
        top_k: Max results (default from config).
        filter_dict: Optional pre-filter.

    Returns:
        List[Dict]: Search results.
    """
    if top_k is None:
        top_k = config.TOP_K_RESULTS

    return vector_search_single(
        query_embedding=query_embedding,
        index_name="embedding_brief_index",
        path="embedding_brief",
        top_k=top_k,
        filter_dict=filter_dict,
    )


def search_by_camera(
    query_embedding: List[float],
    cam_id: str,
    top_k: int = None,
) -> List[Dict[str, Any]]:
    """
    Perform vector search filtered to a specific camera.

    Args:
        query_embedding: The query embedding vector.
        cam_id: Camera identifier to filter results.
        top_k: Maximum number of results.

    Returns:
        List[Dict]: Search results from the specified camera only.
    """
    return vector_search(
        query_embedding=query_embedding,
        top_k=top_k,
        filter_dict={"cam_id": cam_id},
    )


def search_by_time_range(
    query_embedding: List[float],
    start_ts: int,
    end_ts: int,
    top_k: int = None,
) -> List[Dict[str, Any]]:
    """
    Perform vector search filtered to a specific time range.

    Args:
        query_embedding: The query embedding vector.
        start_ts: Start timestamp (inclusive).
        end_ts: End timestamp (inclusive).
        top_k: Maximum number of results.

    Returns:
        List[Dict]: Search results within the specified time range.
    """
    return vector_search(
        query_embedding=query_embedding,
        top_k=top_k,
        filter_dict={"timestamp": {"$gte": start_ts, "$lte": end_ts}},
    )


def get_vector_search_index_info() -> Dict[str, Any]:
    """
    Get information about the vector search indexes.

    Returns:
        Dict: Index existence / status information.
    """
    try:
        db = get_db()
        collection = db[config.COLLECTION_FRAME_EMBEDDINGS]
        indexes = list(collection.list_search_indexes())

        found = {}
        for idx in indexes:
            name = idx.get("name", "")
            for expected_name, _ in _INDEX_MAP:
                if name == expected_name:
                    found[name] = {
                        "exists": True,
                        "status": idx.get("status", "unknown"),
                        "queryable": idx.get("queryable", False),
                    }
        return found if found else {"exists": False, "message": "No vector indexes found"}

    except Exception as e:
        return {"exists": False, "error": str(e)}
